/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fpt.dn.gui.design;

import javax.swing.JPanel;

/**
 *
 * @author WindzLord
 */
public class FrameTabbedPanel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrameTabbedPanel() {
        initComponents();
    }
    
    public JPanel getPanelMain() {
        return panelMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        btnLearn = new javax.swing.JButton();
        tabbedPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setLayout(new java.awt.BorderLayout());

        btnLearn.setText("Learn");
        panelMain.add(btnLearn, java.awt.BorderLayout.PAGE_END);

        tabbedPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabbedPanelPropertyChange(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());
        tabbedPanel.addTab("tab1", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        tabbedPanel.addTab("tab2", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        tabbedPanel.addTab("tab3", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());
        tabbedPanel.addTab("tab4", jPanel4);

        panelMain.add(tabbedPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabbedPanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabbedPanelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tabbedPanelPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new FrameTabbedPanel().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLearn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTabbedPane tabbedPanel;
    // End of variables declaration//GEN-END:variables
}
