/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fpt.dn.gui;

import com.fpt.dn.bo.Methods;
import com.fpt.dn.dao.LessonData;
import com.fpt.dn.entity.DNObject;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author WindzLord
 */
public class LearnVocaPanel extends javax.swing.JFrame {

    private JButton buttonStart;
    private JPanel panelButtonStart;
    private List<DNObject> listVocab;
    private DNObject currentQues;
    private int correct;
    private int incorrect;
    private String lesson;

    /**
     * Creates new form NewJFrame
     *
     * @param lesson
     */
    public LearnVocaPanel(String lesson) {
        initComponents();
        setLesson(lesson);
        initData();
        initScreen();
        addListeners();
    }

    public JPanel getPanelMain() {
        return panelMain;
    }

    private void setLesson(String lesson) {
        this.lesson = lesson;
    }

    private void initScreen() {
        buttonStart = new JButton("Start");
        buttonStart.setFont(new Font("Dialog", 0, 30));
        panelButtonStart = new JPanel(new BorderLayout());
        panelButtonStart.add(buttonStart, BorderLayout.SOUTH);
        panelMain.remove(panelCenter);
        panelMain.add(panelButtonStart);
        repaint();
    }

    private void initData() {
        listVocab = new LessonData("1", lesson).getListVocab();
        correct = incorrect = 0;

        label_icon_remain.setIcon(Methods.newImageIcon("src/icon/ic_remain.png", 60, 60));
        label_icon_remain.setText(String.format("%-5s", "" + listVocab.size()));
        label_icon_remain.setFont(new Font("Dialog", 0, 24));

        label_icon_correct.setIcon(Methods.newImageIcon("src/icon/ic_correct.png", 60, 60));
        label_icon_correct.setText(String.format("%-5s", "" + correct));
        label_icon_correct.setFont(new Font("Dialog", 0, 24));

        label_icon_incorrect.setIcon(Methods.newImageIcon("src/icon/ic_incorrect.png", 60, 60));
        label_icon_incorrect.setText(String.format("%-5s", "" + incorrect));
        label_icon_incorrect.setFont(new Font("Dialog", 0, 24));

        nextQuestion();
    }

    private void nextQuestion() {
        if (listVocab.isEmpty()) {
            return;
        }
        currentQues = listVocab.get(Methods.getRandom(listVocab.size()));

        labelQuestion.setText(currentQues.getValue());
        textFieldAnswer.setText("Enter your answer                           ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label_space_0 = new javax.swing.JLabel();
        label_icon_remain = new javax.swing.JLabel();
        label_space_1 = new javax.swing.JLabel();
        label_icon_correct = new javax.swing.JLabel();
        label_space_2 = new javax.swing.JLabel();
        label_icon_incorrect = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelQuestion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textFieldAnswer = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnStartAgain = new javax.swing.JButton();
        label_space_3 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setLayout(new java.awt.BorderLayout());

        panelTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 40, 1));

        labelTitle.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        labelTitle.setText("    Learn Vocabulary    ");
        labelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelTop.add(labelTitle);

        panelMain.add(panelTop, java.awt.BorderLayout.PAGE_START);

        panelCenter.setLayout(new java.awt.GridLayout(0, 1));

        label_space_0.setText("       ");
        jPanel2.add(label_space_0);
        jPanel2.add(label_icon_remain);

        label_space_1.setText("     ");
        jPanel2.add(label_space_1);
        jPanel2.add(label_icon_correct);

        label_space_2.setText("     ");
        jPanel2.add(label_space_2);
        jPanel2.add(label_icon_incorrect);

        panelCenter.add(jPanel2);

        labelQuestion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelQuestion.setText("Người kia");
        jPanel3.add(labelQuestion);

        panelCenter.add(jPanel3);

        textFieldAnswer.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textFieldAnswer.setText("Enter your answer                           ");
        textFieldAnswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldAnswerFocusGained(evt);
            }
        });
        jPanel4.add(textFieldAnswer);

        panelCenter.add(jPanel4);

        btnStartAgain.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnStartAgain.setText("Start again");
        btnStartAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartAgainActionPerformed(evt);
            }
        });
        jPanel5.add(btnStartAgain);

        label_space_3.setText("                                                      ");
        jPanel5.add(label_space_3);

        btnNext.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel5.add(btnNext);

        panelCenter.add(jPanel5);

        panelMain.add(panelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAnswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldAnswerFocusGained
        // TODO add your handling code here:
        textFieldAnswer.setText("");
    }//GEN-LAST:event_textFieldAnswerFocusGained

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        listVocab.remove(currentQues);
        if (listVocab.isEmpty()) {
            btnNext.setEnabled(false);
            labelQuestion.setText("Done");
        }
        label_icon_remain.setText(String.format("%-5s", "" + listVocab.size()));

        String anwser = textFieldAnswer.getText();
        if (anwser.equals(currentQues.getKey())) {
            correct++;
        } else {
            incorrect++;
        }
        label_icon_correct.setText(String.format("%-5s", "" + correct));
        label_icon_incorrect.setText(String.format("%-5s", "" + incorrect));

        nextQuestion();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnStartAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartAgainActionPerformed
        // TODO add your handling code here:
        initData();
        btnNext.setEnabled(true);
    }//GEN-LAST:event_btnStartAgainActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStartAgain;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel label_icon_correct;
    private javax.swing.JLabel label_icon_incorrect;
    private javax.swing.JLabel label_icon_remain;
    private javax.swing.JLabel label_space_0;
    private javax.swing.JLabel label_space_1;
    private javax.swing.JLabel label_space_2;
    private javax.swing.JLabel label_space_3;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTextField textFieldAnswer;
    // End of variables declaration//GEN-END:variables

    private void addListeners() {
        buttonStart.addActionListener((ActionEvent e) -> {
            panelMain.remove(panelButtonStart);
            panelMain.add(panelCenter);
            MainLessonPanel.instance.refreshScreen();
        });

    }

}
