/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fpt.dn.gui;

import com.fpt.dn.bo.Methods;
import com.fpt.dn.dao.LessonData;
import com.fpt.dn.entity.DNObject;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author WindzLord
 */
public class LearnVocabPanel extends javax.swing.JFrame {

    private JButton buttonStart;
    private JPanel panelButtonStart;
    private List<DNObject> listVocab;
    private DNObject currentQues;
    private int correct;
    private int incorrect;
    private String lesson;
    private final String begeinText = "Enter your answer                           ";

    /**
     * Creates new form LearnVocabPanel
     *
     * @param lesson
     */
    public LearnVocabPanel(String lesson) {
        initComponents();
        setLesson(lesson);
        initData();
        initScreen();
        addListeners();
    }

    public JPanel getPanelMain() {
        return panelMain;
    }

    private void setLesson(String lesson) {
        this.lesson = lesson;
    }

    private void initScreen() {

        buttonStart = new JButton("Start");
        buttonStart.setFont(new Font("Dialog", 0, 24));
        panelButtonStart = new JPanel(new BorderLayout());
        panelButtonStart.add(buttonStart, BorderLayout.SOUTH);
        panelMain.remove(panelCenter);
        panelMain.add(panelButtonStart);
        repaint();
    }

    private void initData() {
        listVocab = new LessonData("1", lesson).getListVocab();
        correct = incorrect = 0;

        label_icon_remain.setIcon(Methods.newImageIcon("src/icon/ic_remain.png", 60, 60));
        label_icon_remain.setText(String.format("%-5s", "" + listVocab.size()));
        label_icon_remain.setFont(new Font("Dialog", 0, 24));

        label_icon_correct.setIcon(Methods.newImageIcon("src/icon/ic_correct.png", 60, 60));
        label_icon_correct.setText(String.format("%-5s", "" + correct));
        label_icon_correct.setFont(new Font("Dialog", 0, 24));

        label_icon_incorrect.setIcon(Methods.newImageIcon("src/icon/ic_incorrect.png", 60, 60));
        label_icon_incorrect.setText(String.format("%-5s", "" + incorrect));
        label_icon_incorrect.setFont(new Font("Dialog", 0, 24));

        nextQuestion();
    }

    private void nextQuestion() {
        labelResult.setText("");
        labelHint.setText("");
        textFieldAnswer.setText("");
        if (listVocab.isEmpty()) {
            return;
        }
        currentQues = listVocab.get(Methods.getRandom(listVocab.size()));

        labelQuestion.setText(currentQues.getValue());
        textFieldAnswer.setText(begeinText);
        textFieldAnswer.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        panel_no_1 = new javax.swing.JPanel();
        label_space_1 = new javax.swing.JLabel();
        label_icon_remain = new javax.swing.JLabel();
        label_space_2 = new javax.swing.JLabel();
        label_icon_correct = new javax.swing.JLabel();
        label_space_3 = new javax.swing.JLabel();
        label_icon_incorrect = new javax.swing.JLabel();
        panel_no_2 = new javax.swing.JPanel();
        panel_2_top = new javax.swing.JPanel();
        labelQuestion = new javax.swing.JLabel();
        panel_2_bot = new javax.swing.JPanel();
        labelHint = new javax.swing.JLabel();
        panel_no_3 = new javax.swing.JPanel();
        textFieldAnswer = new javax.swing.JTextField();
        labelResult = new javax.swing.JLabel();
        panel_no_4 = new javax.swing.JPanel();
        buttonRestart = new javax.swing.JButton();
        label_space_4 = new javax.swing.JLabel();
        buttonNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setLayout(new java.awt.BorderLayout());

        panelTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 40, 1));

        labelTitle.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        labelTitle.setText("    Learn Vocabulary    ");
        labelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelTop.add(labelTitle);

        panelMain.add(panelTop, java.awt.BorderLayout.PAGE_START);

        panelCenter.setLayout(new java.awt.GridLayout(0, 1));

        label_space_1.setText("       ");
        panel_no_1.add(label_space_1);
        panel_no_1.add(label_icon_remain);

        label_space_2.setText("     ");
        panel_no_1.add(label_space_2);
        panel_no_1.add(label_icon_correct);

        label_space_3.setText("     ");
        panel_no_1.add(label_space_3);
        panel_no_1.add(label_icon_incorrect);

        panelCenter.add(panel_no_1);

        panel_no_2.setLayout(new java.awt.BorderLayout());

        labelQuestion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelQuestion.setText("Người kia");
        panel_2_top.add(labelQuestion);

        panel_no_2.add(panel_2_top, java.awt.BorderLayout.PAGE_START);

        labelHint.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelHint.setForeground(java.awt.Color.ORANGE);
        panel_2_bot.add(labelHint);

        panel_no_2.add(panel_2_bot, java.awt.BorderLayout.PAGE_END);

        panelCenter.add(panel_no_2);

        textFieldAnswer.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textFieldAnswer.setText("Enter your answer                           ");
        textFieldAnswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldAnswerFocusGained(evt);
            }
        });
        panel_no_3.add(textFieldAnswer);

        labelResult.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        panel_no_3.add(labelResult);

        panelCenter.add(panel_no_3);

        buttonRestart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonRestart.setText("Start again");
        buttonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestartActionPerformed(evt);
            }
        });
        panel_no_4.add(buttonRestart);

        label_space_4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_space_4.setText("                               ");
        panel_no_4.add(label_space_4);

        buttonNext.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonNext.setText("Next");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });
        panel_no_4.add(buttonNext);

        panelCenter.add(panel_no_4);

        panelMain.add(panelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        // TODO add your handling code here:
        if ("".equals(labelResult.getText())) {
            if (textFieldAnswerActionPerformed(null)) {
                textFieldAnswer.setText("");
            }
            return;
        }

        listVocab.remove(currentQues);
        if (listVocab.isEmpty()) {
            buttonNext.setEnabled(false);
            labelQuestion.setText("Done");
        }
        label_icon_remain.setText(String.format("%-5s", "" + listVocab.size()));

        nextQuestion();
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestartActionPerformed
        // TODO add your handling code here:
        initData();
        buttonNext.setEnabled(true);
        textFieldAnswer.setEnabled(true);
    }//GEN-LAST:event_buttonRestartActionPerformed

    private void textFieldAnswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldAnswerFocusGained
        // TODO add your handling code here:
        textFieldAnswer.setText("");
    }//GEN-LAST:event_textFieldAnswerFocusGained

    private boolean textFieldAnswerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        textFieldAnswer.setEnabled(false);
        labelHint.setText(currentQues.getKey());

        String anwser = textFieldAnswer.getText();
        if (anwser.equals(currentQues.getKey())) {
            labelResult.setForeground(Color.GREEN);
            labelResult.setText("Correct");
            correct++;
        } else {
            labelResult.setForeground(Color.RED);
            labelResult.setText("Incorrect");
            incorrect++;
        }
        label_icon_correct.setText(String.format("%-5s", "" + correct));
        label_icon_incorrect.setText(String.format("%-5s", "" + incorrect));
        return (begeinText.equals(textFieldAnswer.getText()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonRestart;
    private javax.swing.JLabel labelHint;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel label_icon_correct;
    private javax.swing.JLabel label_icon_incorrect;
    private javax.swing.JLabel label_icon_remain;
    private javax.swing.JLabel label_space_1;
    private javax.swing.JLabel label_space_2;
    private javax.swing.JLabel label_space_3;
    private javax.swing.JLabel label_space_4;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panel_2_bot;
    private javax.swing.JPanel panel_2_top;
    private javax.swing.JPanel panel_no_1;
    private javax.swing.JPanel panel_no_2;
    private javax.swing.JPanel panel_no_3;
    private javax.swing.JPanel panel_no_4;
    private javax.swing.JTextField textFieldAnswer;
    // End of variables declaration//GEN-END:variables

    private void addListeners() {
        buttonStart.addActionListener((ActionEvent e) -> {
            panelMain.remove(panelButtonStart);
            panelMain.add(panelCenter);
            MainLessonPanel.instance.refreshScreen();
        });

        textFieldAnswer.addActionListener((ActionEvent e) -> {
            textFieldAnswerActionPerformed(e);
        });
    }

}
