/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fpt.dn.gui;

import com.fpt.dn.entity.DNObject;
import javax.swing.JPanel;

/**
 *
 * @author WindzLord
 */
public class LearnGramPanel extends javax.swing.JFrame {

    /**
     * Creates new form LearnGramPanel
     *
     * @param grammar
     */
    public LearnGramPanel(DNObject grammar) {
        initComponents();
        labelKey.setText(grammar.getKey().substring(5));
        textAreaValue.setText(grammar.getValue());
    }

    public JPanel getPanelMain() {
        return panelMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelKey = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textAreaValue = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setLayout(new java.awt.BorderLayout());

        panelTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 40, 1));

        labelTitle.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        labelTitle.setText("    Grammar Explanation    ");
        labelTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelTop.add(labelTitle);

        panelMain.add(panelTop, java.awt.BorderLayout.PAGE_START);

        panelCenter.setLayout(new java.awt.BorderLayout());

        labelKey.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel1.add(labelKey);

        panelCenter.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        textAreaValue.setEditable(false);
        textAreaValue.setBackground(new java.awt.Color(240, 240, 241));
        textAreaValue.setColumns(20);
        textAreaValue.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textAreaValue.setForeground(new java.awt.Color(51, 51, 55));
        textAreaValue.setLineWrap(true);
        textAreaValue.setRows(5);
        textAreaValue.setWrapStyleWord(true);
        textAreaValue.setPreferredSize(new java.awt.Dimension(400, 95));
        jPanel2.add(textAreaValue);

        panelCenter.add(jPanel2, java.awt.BorderLayout.CENTER);

        panelMain.add(panelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelKey;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTextArea textAreaValue;
    // End of variables declaration//GEN-END:variables
}
