/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fpt.dn.gui;

import com.fpt.dn.bo.Methods;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author WindzLord
 */
public class LearnVocaPanel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public LearnVocaPanel() {
        initComponents();
        myInit();
    }

    public JPanel getPanelMain() {
        return panelMain;
    }

    private void myInit() {
        label_icon_remain.setIcon(Methods.newImageIcon("src/icon/ic_remain.png", 60, 60));
        label_icon_remain.setText(String.format("%-5s", "60"));
        label_icon_remain.setFont(new Font("Dialog", 0, 24));
        
        label_icon_correct.setIcon(Methods.newImageIcon("src/icon/ic_correct.png", 60, 60));
        label_icon_correct.setText(String.format("%-5s", "0"));
        label_icon_correct.setFont(new Font("Dialog", 0, 24));
        
        label_icon_incorrect.setIcon(Methods.newImageIcon("src/icon/ic_incorrect.png", 60, 60));
        label_icon_incorrect.setText(String.format("%-5s", "0"));
        label_icon_incorrect.setFont(new Font("Dialog", 0, 24));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label_space_0 = new javax.swing.JLabel();
        label_icon_remain = new javax.swing.JLabel();
        label_space_1 = new javax.swing.JLabel();
        label_icon_correct = new javax.swing.JLabel();
        label_space_2 = new javax.swing.JLabel();
        label_icon_incorrect = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelQuestion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textFieldAnswer = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnStartAgain = new javax.swing.JButton();
        label_space_3 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setLayout(new java.awt.BorderLayout());

        panelTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 40, 1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        jLabel1.setText("    Learn Vocabulary    ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelTop.add(jLabel1);

        panelMain.add(panelTop, java.awt.BorderLayout.PAGE_START);

        panelCenter.setLayout(new java.awt.GridLayout(0, 1));

        label_space_0.setText("       ");
        jPanel2.add(label_space_0);
        jPanel2.add(label_icon_remain);

        label_space_1.setText("     ");
        jPanel2.add(label_space_1);
        jPanel2.add(label_icon_correct);

        label_space_2.setText("     ");
        jPanel2.add(label_space_2);
        jPanel2.add(label_icon_incorrect);

        panelCenter.add(jPanel2);

        labelQuestion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelQuestion.setText("Người kia");
        jPanel3.add(labelQuestion);

        panelCenter.add(jPanel3);

        textFieldAnswer.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textFieldAnswer.setText("Enter your answer                 ");
        textFieldAnswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldAnswerFocusGained(evt);
            }
        });
        jPanel4.add(textFieldAnswer);

        panelCenter.add(jPanel4);

        btnStartAgain.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnStartAgain.setText("Start again");
        jPanel5.add(btnStartAgain);

        label_space_3.setText("                                                      ");
        jPanel5.add(label_space_3);

        btnNext.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnNext.setText("Next");
        jPanel5.add(btnNext);

        panelCenter.add(jPanel5);

        panelMain.add(panelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAnswerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldAnswerFocusGained
        // TODO add your handling code here:
        textFieldAnswer.setText("");
    }//GEN-LAST:event_textFieldAnswerFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new LearnVocaPanel().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStartAgain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JLabel label_icon_correct;
    private javax.swing.JLabel label_icon_incorrect;
    private javax.swing.JLabel label_icon_remain;
    private javax.swing.JLabel label_space_0;
    private javax.swing.JLabel label_space_1;
    private javax.swing.JLabel label_space_2;
    private javax.swing.JLabel label_space_3;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTextField textFieldAnswer;
    // End of variables declaration//GEN-END:variables
}
